02-Flask会话技术和Flask模板语言/FlaskPro1——会话技术Cookie和session/App/__init__.py
# 初始化文件
from flask import Flask, render_template
from .views import blue


def create_app():
    app = Flask(__name__)

    # 注册蓝图
    app.register_blueprint(blueprint=blue)
    # session 配置
    print(app.config)
    '''<Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 
    'PROPAGATE_EXCEPTIONS': None, 'SECRET_KEY': None, 
    'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 
    'USE_X_SENDFILE': False, 'SERVER_NAME': None, 
    'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 
    'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 
    'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 
    'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False,  'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': None, 'JSON_SORT_KEYS': None, 'JSONIFY_PRETTYPRINT_REGULAR': None, 'JSONIFY_MIMETYPE': None, 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093}>
'''

    app.config['SECRET_KEY'] = 'abc123'

    return app

02-Flask会话技术和Flask模板语言/FlaskPro1——会话技术Cookie和session/App/views.py
import datetime

from flask import Blueprint, render_template, request, redirect, session
from .models import *

# 蓝图
blue = Blueprint('user', __name__)

# 首页
@blue.route('/')
@blue.route('/home/')
def home():
    # 4. 获取cookie
    #username = request.cookies.get('user')
    # 获取session
    username = session.get('user')
    return render_template('home.html', username=username)

# 登陆
@blue.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        # 1. 获取前端提交过来的数据
        username = request.form.get('username')
        password = request.form.get('password')

        # 2. 实现登陆功能 用户名和密码验证
        if username =='lisi' and password=='123':
            response = redirect('/home')

            # 3. 设置cookie
            # cookie 中不能用中文
            # response.set_cookie('user', username)  # 默认浏览器关闭，cookie失效
            # 过期时间
            # max_age:秒
            # expires: 指定的datatime日期
            # response.set_cookie('user', username, max_age=3600*24*7)
            #response.set_cookie('user', username, expires=datetime.datetime(2025, 1, 18))

            # 设置session
            session['user'] = username
            session.permanent=True
            return response
        else:
            return '用户名或密码错误'

# 注销
@blue.route('/logout/')
def logout():
    # 5. 删除cookie
    response = redirect('/home/')

    #response.delete_cookie('user')
    # 删除session
    session.pop('user')
    # session.clear() # 慎用，会删除服务器下所有session

    return response

02-Flask会话技术和Flask模板语言/FlaskPro1——会话技术Cookie和session/App/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h2>首页</h2>
    <hr>
    {% if  username %}
        <p>
            当前登陆用户:{{ username }}
            <a href="/logout/">注销</a>
        </p>
    {% else %}
        <a href="/login/">登陆</a>
    {% endif %}


</body>
</html>

02-Flask会话技术和Flask模板语言/FlaskPro1——会话技术Cookie和session/App/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
    <h2>登陆</h2>
    <hr>

<!--    <form action="" method="post">-->
    <form action="{{ url_for('user.login')}}" method="post">
<!--    <form action="/login/" method="post">-->
        <p>
            用户名:<input type="text" name="username">
        </p>
        <p>
            密码:<input type="password" name="password">
        </p>
        <p>
            <button>提交</button>
        </p>
    </form>
</body>
</html>